---
- hosts: "{{ target }}"
  become: yes
  tasks:

#  This tasks will be added once a password repository has been defined.
#    - name: When applicable use password values in the password file
#      include_vars:
#        file: ../files/passwords.yml 




# Copy CAM-Key UI configurations
  - name: Copying system configuration
    copy:
      src: "{{ sys_config_src }}"
      dest: "{{ sys_config }}"
      mode: "0664"
      group: www
  - name: Copying app configuration for development
    copy:
      src: "{{ app_config_src }}"
      dest: "{{ app_dev_config }}"
      mode: "0664"
      group: www
    when: mysql_role == "secondary"
  - name: Copying app configuration for production
    copy:
      src: "{{ app_config_src }}"
      dest: "{{ app_prod_config }}"
      mode: "0664"
      group: www
    when: mysql_role == "primary"